server.port=8083
spring.application.name=assessment

spring.security.user.name=admin
spring.security.user.password=admin

patient.service.url=http://localhost:8080
note.service.url=http://localhost:8082
